before:
  hooks:
    - go mod download
project_name: "{{ .ProjectName }}"
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "broemp/{{ .ProjectName }}:latest-arm64v8"
      - "broemp/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
      - "broemp/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
      - "broemp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
  - image_templates:
      - "broemp/{{ .ProjectName }}:latest-amd64"
      - "broemp/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "broemp/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "broemp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
docker_manifests:
  - name_template: "broemp/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - broemp/{{ .ProjectName }}:{{ .Version }}-amd64
      - broemp/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: broemp/{{ .ProjectName }}:latest
    image_templates:
      - broemp/{{ .ProjectName }}:{{ .Version }}-amd64
      - broemp/{{ .ProjectName }}:{{ .Version }}-arm64v8
