# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "broemp/growbro:{{ .Tag }}-amd64"
      - "broemp/growbro:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "broemp/growbro:{{ .Tag }}-arm64"
      - "broemp/growbro:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

# .goreleaser.yaml
docker_manifests:
  - name_template: "broemp/growbro:{{ .Tag }}"
    image_templates:
      - "broemp/growbro:{{ .Tag }}-amd64"
      - "broemp/growbro:{{ .Tag }}-arm64"
  - name_template: "broemp/growbro:latest"
    image_templates:
      - "broemp/growbro:latest-amd64"
      - "broemp/growbro:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
