before:
  hooks:
    - go mod download
project_name: "growbro"
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "broemp/growbro:latest-arm64v8"
      - "broemp/growbro:{{ .Tag }}-arm64v8"
      - "broemp/growbro:v{{ .Major }}-arm64v8"
      - "broemp/growbro:v{{ .Major }}.{{ .Minor }}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title=growbro
      - --label=org.opencontainers.image.description=growbro
      - --label=org.opencontainers.image.version={{ .Version }}
  - image_templates:
      - "broemp/growbro:latest-amd64"
      - "broemp/growbro:{{ .Tag }}-amd64"
      - "broemp/growbro:v{{ .Major }}-amd64"
      - "broemp/growbro:v{{ .Major }}.{{ .Minor }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title=growbro
      - --label=org.opencontainers.image.description=growbro
      - --label=org.opencontainers.image.version={{ .Version }}
docker_manifests:
  - name_template: "broemp/growbro:{{ .Version }}"
    image_templates:
      - broemp/growbro:{{ .Version }}-amd64
      - broemp/growbro:{{ .Version }}-arm64v8
  - name_template: broemp/growbro:latest
    image_templates:
      - broemp/growbro:{{ .Version }}-amd64
      - broemp/growbro:{{ .Version }}-arm64v8
