// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error
	GetToken(ctx context.Context, token string) (GetTokenRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
