name: Build Docker

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          username: broemp
          password: ${{secrets.DH_TOKEN}}
      - name: Docker meta
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            broemp/growbro
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            Version=${{  env.TAG }}
            GitCommit=${{ github.sha }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
